Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 9999

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Enabled: false

Lint/Debugger:
  Exclude:
    - 'bin/console'
